name: PUBLISH TO WEBSITE
on:
  push:
    branches: [ main ]
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Wait for 120 seconds, to give the minimize pictures action some time
      uses: kibertoad/wait-action@1.0.1
      with:
        time: '120s'
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_username_live }}
        password: ${{ secrets.ftp_password_live }}
