name: PUBLISH TO STAGE
on:
  push:
    branches: [ stage ]
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_username_stage }}
        password: ${{ secrets.ftp_password_stage }}
